import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema.
 *
 * Two owners, one migration chain:
 *  - better-auth owns `user`, `session`, `account`, `verification`,
 *    `organization`, `member`, `invitation`. That DDL is generated by
 *    `pnpm auth:sql` (see scripts/print-auth-sql.ts) and pasted here rather than
 *    applied by better-auth's own CLI, so `pnpm db:migration:run` remains the
 *    single way the schema ever changes.
 *  - TypeORM owns application tables (`audit_logs`).
 *
 * Regenerate the better-auth half with `pnpm auth:sql` after changing plugins or
 * additional fields in auth.config.ts, and add a NEW migration for the delta —
 * do not edit this one once it has been applied anywhere.
 */
export class InitialSchema1786360000000 implements MigrationInterface {
  name = 'InitialSchema1786360000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // --- better-auth: identity -------------------------------------------
    await queryRunner.query(
      `CREATE TABLE "user" ("id" text NOT NULL PRIMARY KEY, "name" text NOT NULL, "email" text NOT NULL UNIQUE, "emailVerified" boolean NOT NULL, "image" text, "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, "role" text)`
    );
    await queryRunner.query(
      `CREATE TABLE "session" ("id" text NOT NULL PRIMARY KEY, "expiresAt" timestamptz NOT NULL, "token" text NOT NULL UNIQUE, "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" timestamptz NOT NULL, "ipAddress" text, "userAgent" text, "userId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE, "activeOrganizationId" text)`
    );
    await queryRunner.query(
      `CREATE TABLE "account" ("id" text NOT NULL PRIMARY KEY, "accountId" text NOT NULL, "providerId" text NOT NULL, "userId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" timestamptz NOT NULL)`
    );
    await queryRunner.query(
      `CREATE TABLE "verification" ("id" text NOT NULL PRIMARY KEY, "identifier" text NOT NULL, "value" text NOT NULL, "expiresAt" timestamptz NOT NULL, "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL)`
    );

    // --- better-auth: organizations --------------------------------------
    await queryRunner.query(
      `CREATE TABLE "organization" ("id" text NOT NULL PRIMARY KEY, "name" text NOT NULL, "slug" text NOT NULL UNIQUE, "logo" text, "createdAt" timestamptz NOT NULL, "metadata" text)`
    );
    await queryRunner.query(
      `CREATE TABLE "member" ("id" text NOT NULL PRIMARY KEY, "organizationId" text NOT NULL REFERENCES "organization" ("id") ON DELETE CASCADE, "userId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE, "role" text NOT NULL, "createdAt" timestamptz NOT NULL)`
    );
    await queryRunner.query(
      `CREATE TABLE "invitation" ("id" text NOT NULL PRIMARY KEY, "organizationId" text NOT NULL REFERENCES "organization" ("id") ON DELETE CASCADE, "email" text NOT NULL, "role" text, "status" text NOT NULL, "expiresAt" timestamptz NOT NULL, "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, "inviterId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE)`
    );

    await queryRunner.query(
      `CREATE INDEX "session_userId_idx" ON "session" ("userId")`
    );
    await queryRunner.query(
      `CREATE INDEX "account_userId_idx" ON "account" ("userId")`
    );
    await queryRunner.query(
      `CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier")`
    );
    await queryRunner.query(
      `CREATE INDEX "member_organizationId_idx" ON "member" ("organizationId")`
    );
    await queryRunner.query(
      `CREATE INDEX "member_userId_idx" ON "member" ("userId")`
    );
    await queryRunner.query(
      `CREATE INDEX "invitation_organizationId_idx" ON "invitation" ("organizationId")`
    );
    await queryRunner.query(
      `CREATE INDEX "invitation_email_idx" ON "invitation" ("email")`
    );

    // A user may hold exactly one membership per organization. Without this,
    // a re-accepted invitation silently creates a duplicate member row.
    await queryRunner.query(
      `CREATE UNIQUE INDEX "member_org_user_uq" ON "member" ("organizationId", "userId")`
    );

    // --- application tables ----------------------------------------------
    await queryRunner.query(
      `CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying(100) NOT NULL, "actor_id" text, "resource" character varying(100) NOT NULL, "resource_id" text, "organization_id" text, "ip_address" character varying(45), "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_audit_logs" PRIMARY KEY ("id"))`
    );
    // Index names are TypeORM's generated hashes, not friendly names. They must
    // match what @Index() on AuditLog produces, or `migration:generate` reports
    // a rename on every run forever.
    await queryRunner.query(
      `CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id")`
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_145f35b204c731ba7fc1a0be0e" ON "audit_logs" ("organization_id")`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "audit_logs"`);
    await queryRunner.query(`DROP TABLE "invitation"`);
    await queryRunner.query(`DROP TABLE "member"`);
    await queryRunner.query(`DROP TABLE "organization"`);
    await queryRunner.query(`DROP TABLE "verification"`);
    await queryRunner.query(`DROP TABLE "account"`);
    await queryRunner.query(`DROP TABLE "session"`);
    await queryRunner.query(`DROP TABLE "user"`);
  }
}
